# Generated by Django 3.2.6 on 2021-08-05 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customer_manager'),
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.customer'),
        ),
        migrations.AlterField(
            model_name='job',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_job', to='accounts.employee'),
        ),
        migrations.AlterField(
            model_name='job',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supervised_job', to='accounts.manager'),
        ),
        migrations.AlterField(
            model_name='labourunit',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.employee'),
        ),
    ]
