# Generated by Django 3.2.6 on 2021-08-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20210805_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='reg',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
