# Generated by Django 3.2.6 on 2021-08-10 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_auto_20210810_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='time_spent',
        ),
    ]
