# Generated by Django 3.2.6 on 2021-08-10 12:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customer_manager'),
        ('cars', '0007_remove_job_time_spent'),
    ]

    operations = [
        migrations.AddField(
            model_name='labourunit',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partunit',
            name='added_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='accounts.employee'),
            preserve_default=False,
        ),
    ]
