# Generated by Django 3.2.6 on 2021-08-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_remove_labourunit_consumables'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
