# Generated by Django 3.2.6 on 2021-08-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_auto_20210824_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='partunit',
            name='cost_each',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
