# Generated by Django 3.2.6 on 2021-09-03 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0002_partsorder_partsorderunit'),
        ('accounts', '0003_customer_manager'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0017_labourunit_hourly_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.manager')),
                ('job', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='cars.job')),
                ('part', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='parts.part')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
