# Generated by Django 3.2.6 on 2021-08-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0016_invoice_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='labourunit',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
